### ISSUE TITLE
If the replies are sorted by anything, the script execution fails.

### ISSUE THREAD

**Issue by llagerlof** [sainathadapa/reddit2mobi#1]
To reproduce, try this:

```
node run_reddit2html.js http://www.reddit.com/r/AskReddit/comments/1sn8ki/what_is_a_skill_someone_can_learn_in_6_months/?sort=confidence 4 > out.htm
```

The error itself:

```
undefined:1
<!doctype html><html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="
^
SyntaxError: Unexpected token <
    at Object.parse (native)
    at IncomingMessage.<anonymous> (C:\Apps\node_modules\reddit2html\index.js:43:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

If I remove the sort url parameter, it works:

```
node run_reddit2html.js http://www.reddit.com/r/AskReddit/comments/1sn8ki/what_is_a_skill_someone_can_learn_in_6_months/ 4 > out.htm
```

**Comment by sainathadapa** [comment]
Thanks! I will take a look. Resolving the issue should be simple.

**Comment by sainathadapa** [comment]
I pushed a new version. Please check with the newer version and if it works, close the issue.
